# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubetracker', '0008_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='language',
            field=models.CharField(choices=[('English', 'EN'), ('Portuguese', 'PT'), ('Spanish', 'ES'), ('Arabic', 'AR'), ('Russian', 'RU')], default='English', max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='marketer',
            field=models.CharField(choices=[('Jacob', 'Jacob'), ('Angie', 'Angie'), ('Emily', 'Emily'), ('Louise', 'Louise'), ('Tyler', 'Tyler'), ('Sarah', 'Sarah'), ('Melissa', 'Melissa'), ('Valeria', 'Valeria'), ('Mauricio', 'Mauricio'), ('Noor', 'Noor'), ('Ben', 'Ben'), ('Annie', 'Annie'), ('Juliana', 'Juliana'), ('Toby', 'Toby')], default='Jacob', max_length=30),
        ),
    ]
