# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubetracker', '0010_auto_20170409_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='marketer',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Jacob', 'Jacob'), ('Angie', 'Angie'), ('Emily', 'Emily'), ('Louise', 'Louise'), ('Tyler', 'Tyler'), ('Sarah', 'Sarah'), ('Melissa', 'Melissa'), ('Valeria', 'Valeria'), ('Mauricio', 'Mauricio'), ('Noor', 'Noor'), ('Ben', 'Ben'), ('Annie', 'Annie'), ('Juliana', 'Juliana'), ('Toby', 'Toby')], default='Unknown', max_length=30),
        ),
    ]
